// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auuekkzxhvyodahepmkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dWVra3p4aHZ5b2RhaGVwbWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODU1OTcsImV4cCI6MjA3MDA2MTU5N30.MKLydbXVNdUVZb3c1VnxeYiVraKSVVFy1H4dEUfOVEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});